package com.disasterhelp.webapp.beans;// default package
// Generated 16 Dec, 2015 9:56:42 PM by Hibernate Tools 4.0.0

import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AidAvailable generated by hbm2java
 */
@Entity
@Table(name = "aidAvailable", catalog = "disasterHelp")
public class AidAvailable extends SuperEntity implements java.io.Serializable {

	private Area area;
	private String aidType;
	private Integer isValid;
	private Integer isInvalid;
	private String contactNo;

	public AidAvailable() {
	}

	public AidAvailable(Area area, String aidType, Integer isValid, Integer isInvalid,String contactNo) {
		this.area = area;
		this.aidType = aidType;
		this.isValid = isValid;
		this.isInvalid = isInvalid;
		this.contactNo = contactNo;
	}



	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "area")
	public Area getArea() {
		return this.area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	@Column(name = "aidType", length = 250)
	public String getAidType() {
		return this.aidType;
	}

	public void setAidType(String aidType) {
		this.aidType = aidType;
	}

	@Column(name = "isValid")
	public Integer getIsValid() {
		return this.isValid;
	}

	public void setIsValid(Integer isValid) {
		this.isValid = isValid;
	}

	@Column(name = "isInvalid")
	public Integer getIsInvalid() {
		return this.isInvalid;
	}

	public void setIsInvalid(Integer isInvalid) {
		this.isInvalid = isInvalid;
	}

	@Column(name = "contactNo", length = 45)
	public String getContactNo() {
		return contactNo;
	}

	public void setContactNo(String contactNo) {
		this.contactNo = contactNo;
	}
}
