package com.disasterhelp.webapp.beans;// default package
// Generated 15 Dec, 2015 8:45:27 PM by Hibernate Tools 4.0.0

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Area generated by hbm2java
 */
@Entity
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "area", catalog = "disasterHelp")
public class Area extends SuperEntity implements java.io.Serializable {

	private String areaName;
	private Set<Helpline> helplines = new HashSet<Helpline>(0);
	private Set<Volunteers> volunteerses = new HashSet<Volunteers>(0);
	private Set<AidNeeded> aidNeededs = new HashSet<AidNeeded>(0);
	private Set<AidAvailable> aidAvailables = new HashSet<AidAvailable>(0);

	public Area() {
	}

	public Area(String areaName, Set<Helpline> helplines, Set<Volunteers> volunteerses,
			Set<AidNeeded> aidNeededs, Set<AidAvailable> aidAvailables) {
		this.areaName = areaName;
		this.helplines = helplines;
		this.volunteerses = volunteerses;
		this.aidNeededs = aidNeededs;
		this.aidAvailables = aidAvailables;
	}



	@Column(name = "areaName", length = 60)
	public String getAreaName() {
		return this.areaName;
	}

	public void setAreaName(String areaName) {
		this.areaName = areaName;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "area")
	public Set<Helpline> getHelplines() {
		return this.helplines;
	}

	public void setHelplines(Set<Helpline> helplines) {
		this.helplines = helplines;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "area")
	public Set<Volunteers> getVolunteerses() {
		return this.volunteerses;
	}

	public void setVolunteerses(Set<Volunteers> volunteerses) {
		this.volunteerses = volunteerses;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "area")
	public Set<AidNeeded> getAidNeededs() {
		return this.aidNeededs;
	}

	public void setAidNeededs(Set<AidNeeded> aidNeededs) {
		this.aidNeededs = aidNeededs;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "area")
	public Set<AidAvailable> getAidAvailables() {
		return this.aidAvailables;
	}

	public void setAidAvailables(Set<AidAvailable> aidAvailables) {
		this.aidAvailables = aidAvailables;
	}

}
