package com.disasterhelp.webapp.beans;// default package
// Generated 16 Dec, 2015 9:56:42 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Disaster generated by hbm2java
 */
@Entity
@Table(name = "disaster", catalog = "disasterHelp")
public class Disaster implements java.io.Serializable {

	private Integer id;
	private String disasterName;
	private Set<Volunteers> volunteerses = new HashSet<Volunteers>(0);
	private Set<Helpline> helplines = new HashSet<Helpline>(0);
	private Set<AidAvailable> aidAvailables = new HashSet<AidAvailable>(0);
	private Set<AidNeeded> aidNeededs = new HashSet<AidNeeded>(0);
	private Set<Area> areas = new HashSet<Area>(0);

	public Disaster() {
	}

	public Disaster(String disasterName, Set<Volunteers> volunteerses, Set<Helpline> helplines,
			Set<AidAvailable> aidAvailables, Set<AidNeeded> aidNeededs, Set<Area> areas) {
		this.disasterName = disasterName;
		this.volunteerses = volunteerses;
		this.helplines = helplines;
		this.aidAvailables = aidAvailables;
		this.aidNeededs = aidNeededs;
		this.areas = areas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "disasterName", length = 150)
	public String getDisasterName() {
		return this.disasterName;
	}

	public void setDisasterName(String disasterName) {
		this.disasterName = disasterName;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "disaster")
	public Set<Volunteers> getVolunteerses() {
		return this.volunteerses;
	}

	public void setVolunteerses(Set<Volunteers> volunteerses) {
		this.volunteerses = volunteerses;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "disaster")
	public Set<Helpline> getHelplines() {
		return this.helplines;
	}

	public void setHelplines(Set<Helpline> helplines) {
		this.helplines = helplines;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "disaster")
	public Set<AidAvailable> getAidAvailables() {
		return this.aidAvailables;
	}

	public void setAidAvailables(Set<AidAvailable> aidAvailables) {
		this.aidAvailables = aidAvailables;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "disaster")
	public Set<AidNeeded> getAidNeededs() {
		return this.aidNeededs;
	}

	public void setAidNeededs(Set<AidNeeded> aidNeededs) {
		this.aidNeededs = aidNeededs;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "disaster")
	public Set<Area> getAreas() {
		return this.areas;
	}

	public void setAreas(Set<Area> areas) {
		this.areas = areas;
	}

}
