package com.disasterhelp.webapp.beans;// default package
// Generated 8 Dec, 2015 10:55:44 AM by Hibernate Tools 4.0.0

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MainMenu generated by hbm2java
 */
@Entity
@Cache(usage= CacheConcurrencyStrategy.READ_ONLY)
@Table(name = "mainMenu", catalog = "disasterHelp")
public class MainMenu implements java.io.Serializable {

	private Integer id;
	private String title;
	private String link;
	private Set<SubMenu> subMenus = new HashSet<SubMenu>(0);

	public MainMenu() {
	}

	public MainMenu(String title, String link, Set<SubMenu> subMenus) {
		this.title = title;
		this.link = link;
		this.subMenus = subMenus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Title", length = 50)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "link", length = 150)
	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mainMenu")
	public Set<SubMenu> getSubMenus() {
		return this.subMenus;
	}

	public void setSubMenus(Set<SubMenu> subMenus) {
		this.subMenus = subMenus;
	}

}
