package com.disasterhelp.webapp.beans;// default package
// Generated 8 Dec, 2015 10:55:44 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SubMenu generated by hbm2java
 */
@Entity
@Table(name = "subMenu", catalog = "disasterHelp")
public class SubMenu implements java.io.Serializable {

	private Integer id;
	private MainMenu mainMenu;
	private String title;
	private String link;

	public SubMenu() {
	}

	public SubMenu(MainMenu mainMenu, String title, String link) {
		this.mainMenu = mainMenu;
		this.title = title;
		this.link = link;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mainMenu")
	public MainMenu getMainMenu() {
		return this.mainMenu;
	}

	public void setMainMenu(MainMenu mainMenu) {
		this.mainMenu = mainMenu;
	}

	@Column(name = "title", length = 50)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "link", length = 150)
	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

}
